block2:
  position: [5.0, 3.0, 3.5]
  orientation: [0.0, 0.0, 0.0]

block3:
  position: [5.0, 3.0, 2.5]
  orientation: [0.0, 0.0, 0.0]

block4:
  position: [5.0, 3.0, 1.5]
  orientation: [0.0, 0.0, 0.0]

block5:
  position: [5.0, 3.0, 0.5]
  orientation: [0.0, 0.0, 0.0]