block1:
  type: "static"
  position: [-5.0, 0.0, 0.5]
  orientation: [0.0, 0.0, 0.0]
  color: [0.0, 0.0, 0.0]
  size: 1.0

block2:
  type: "dynamic"
  position: [-5.0, 0.0, 1.5]
  orientation: [0.0, 0.0, 0.0]
  color: [1.0, 0.0, 0.0]
  size: 1.0

block3:
  type: "dynamic"
  position: [-5.0, 0.0, 2.5]
  orientation: [0.0, 0.0, 0.0]
  color: [0.0, 1.0, 0.0]
  size: 1.0

block4:
  type: "dynamic"
  position: [-5.0, 0.0, 3.5]
  orientation: [0.0, 0.0, 0.0]
  color: [0.0, 0.0, 1.0]
  size: 1.0

block5:
  type: "dynamic"
  position: [-5.0, 0.0, 4.5]
  orientation: [0.0, 0.0, 0.0]
  color: [1.0, 1.0, 0.0]
  size: 1.0

robot:
  type: "robot"
  position: [-3.0, -3.0, 0.5]
  orientation: [0.0, 0.0, 0.0]