block2:
  position: [0.0, 0.0, 0.5]
  orientation: [0.0, 0.0, 0.0]

block3:
  position: [0.0, 0.0, 1.5]
  orientation: [0.0, 0.0, 0.0]

block4:
  position: [0.0, 0.0, 2.5]
  orientation: [0.0, 0.0, 0.0]

block5:
  position: [0.0, 0.0, 3.5]
  orientation: [0.0, 0.0, 0.0]

block6:
  position: [0.0, 0.0, 4.5]
  orientation: [0.0, 0.0, 0.0]

block7:
  position: [0.0, 0.0, 5.5]
  orientation: [0.0, 0.0, 0.0]

block8:
  position: [0.0, 0.0, 6.5]
  orientation: [0.0, 0.0, 0.0]

block9:
  position: [0.0, 0.0, 7.5]
  orientation: [0.0, 0.0, 0.0]

block10:
  position: [0.0, 0.0, 8.5]
  orientation: [0.0, 0.0, 0.0]